version: "3.8"
services:
  db:
    image: postgres
    container_name: marketDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: market
  api:
    image: market
    container_name: market
    ports:
      - "8080:8080"
    depends_on:
      - db