
jwt:
    secret: secret
    lifetime: 30m
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/market
    username: postgres
    password: admin
  flyway:
    baseline-on-migrate: true
  mail:
    host: smtp.mail.ru
    port: 465
    username: ds.quicksave@mail.ru
    password: vfUmguPhkskyYh9dbjpt
    test-connection: true
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.mail.ru

