create sequence cart_details_seq start with 1 increment by 1;
create sequence carts_seq start with 1 increment by 1;
create sequence orders_details_seq start with 1 increment by 1;
create sequence orders_seq start with 1 increment by 1;
create sequence products_seq start with 1 increment by 1;
create sequence users_seq start with 1 increment by 1;
create table carts (id integer not null, user_id integer unique, primary key (id));
create table carts_details (amount integer not null, cart_id integer, id integer not null, price float(53) not null, product_id integer, primary key (id));
create table orders (id integer not null, sum numeric(38,2), user_id integer, created timestamp(6), address varchar(255), status varchar(255) check (status in ('NEW','APPROVED','PAID','CLOSED','CANCELED')), primary key (id));
create table orders_details (amount numeric(38,2), id integer not null, order_id integer, price numeric(38,2), product_id integer, primary key (id));
create table products (id integer not null, price float(53), name varchar(255), primary key (id));
create table users (cart_id integer unique, id integer not null, email varchar(255), password varchar(255), role varchar(255) check (role in ('ROLE_USER','ROLE_ADMIN')), username varchar(255), primary key (id));
alter table if exists carts add constraint carts_user_fk foreign key (user_id) references users;
alter table if exists carts_details add constraint carts_details_cart_fk foreign key (cart_id) references carts;
alter table if exists carts_details add constraint carts_details_product_fk foreign key (product_id) references products;
alter table if exists orders add constraint orders_user_fk foreign key (user_id) references users;
alter table if exists orders_details add constraint orders_details_order_fk foreign key (order_id) references orders;
alter table if exists orders_details add constraint orders_details_product_fk foreign key (product_id) references products;
alter table if exists users add constraint users_cart_fk foreign key (cart_id) references carts;