create sequence carts_seq start with 1 increment by 1;
create sequence orders_details_seq start with 1 increment by 1;
create sequence orders_seq start with 1 increment by 1;
create sequence products_seq start with 1 increment by 1;
create sequence users_seq start with 1 increment by 1;
create table carts (id integer not null, user_id integer unique, primary key (id));
create table carts_products (cart_id integer not null, product_id integer not null);
create table orders (id integer not null, sum numeric(38,2), user_id integer, created timestamp(6), address varchar(255), status varchar(255) check (status in ('NEW','APPROVED','PAID','CLOSED','CANCELED')), primary key (id));
create table orders_details (amount numeric(38,2), details_id integer not null unique, id integer not null, order_id integer, price numeric(38,2), product_id integer, primary key (id));
create table products (id integer not null, price numeric(38,2), name varchar(255), primary key (id));
create table users (cart_id integer unique, id integer not null, email varchar(255), name varchar(255), password varchar(255), role varchar(255) check (role in ('CLIENT','ADMIN')), primary key (id));
alter table if exists carts add constraint FK_users_carts foreign key (user_id) references users;
alter table if exists carts_products add constraint FK_products_carts foreign key (product_id) references products;
alter table if exists carts_products add constraint FK_carts_products foreign key (cart_id) references carts;
alter table if exists orders add constraint FK_users_orders foreign key (user_id) references users;
alter table if exists orders_details add constraint FK_orders_details foreign key (order_id) references orders;
alter table if exists orders_details add constraint FK_products_orders foreign key (product_id) references products;
alter table if exists orders_details add constraint FK_details_orders foreign key (details_id) references orders_details;
alter table if exists users add constraint FK_users_carts foreign key (cart_id) references carts;