create sequence carts_seq start with 1 increment by 1;
create sequence orders_details_seq start with 1 increment by 1;
create sequence orders_seq start with 1 increment by 1;
create sequence products_seq start with 1 increment by 1;
create sequence users_seq start with 1 increment by 1;
create table carts (id integer not null, user_id integer unique, primary key (id));
create table carts_products (cart_id integer not null, product_id integer not null, constraint UKm3tb81tdoq5v03tid7bf81p8j unique (cart_id, product_id));
create table orders (id integer not null, sum numeric(38,2), user_id integer, created timestamp(6), address varchar(255), status varchar(255) check (status in ('NEW','APPROVED','PAID','CLOSED','CANCELED')), primary key (id));
create table orders_details (amount numeric(38,2), details_id integer not null unique, id integer not null, order_id integer, price numeric(38,2), product_id integer, primary key (id));
create table products (id integer not null, price numeric(38,2), name varchar(255), primary key (id));
create table users (cart_id integer unique, id integer not null, email varchar(255), password varchar(255), role varchar(255) check (role in ('ROLE_USER','ROLE_ADMIN')), username varchar(255), primary key (id));
alter table if exists carts add constraint FKb5o626f86h46m4s7ms6ginnop foreign key (user_id) references users;
alter table if exists carts_products add constraint FKt3mepi19unnkcmw4683q5wr39 foreign key (product_id) references products;
alter table if exists carts_products add constraint FK3nvguygrfbn661omvvu2uafu5 foreign key (cart_id) references carts;
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table if exists orders_details add constraint FK5o977kj2vptwo70fu7w7so9fe foreign key (order_id) references orders;
alter table if exists orders_details add constraint FKs0r9x49croribb4j6tah648gt foreign key (product_id) references products;
alter table if exists orders_details add constraint FKgvp1k7a3ubdboj3yhnawd5m1p foreign key (details_id) references orders_details;
alter table if exists users add constraint FKdv26y3bb4vdmsr89c9ppnx85w foreign key (cart_id) references carts;